name: Advanced Flask App CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code         #checks out the code from the GitHub repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint code
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run tests
      run: |
        pytest --cov=.

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Login to Azure Container Registry
      run: |
        az acr login --name pycidcdregistry

    - name: Pull Docker Image from ACR
      run: |
        docker pull pycidcdregistry.azurecr.io/my-flask-app:latest

    - name: Run Docker container on port 9090
      run: |
        docker run -d -p 9090:9090 pycidcdregistry.azurecr.io/my-flask-app:latest
